apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-scaler-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: predictive-autoscaler-sa
  namespace: default
roleRef:
  kind: Role
  name: deployment-scaler-role
  apiGroup: rbac.authorization.k8s.io

